### ISSUE TITLE
[Feature Request] Add healthcheck to dockerfile

### ISSUE THREAD

**Issue by Ornias1993** [Boerderij/Varken#185]
**Describe the solution you'd like**
A healthcheck being integrated into the dockerfile

**Describe alternatives you've considered**
Doing it myself, if possible that still would need to be documented which means we could just as well implement it the right way first time.

**Additional context**
It's a health check, not rocket science.

**Comment by samwiseg0** [comment]
Why would this be useful? How would we implement this? 

There is no web interface. It’s either running or not. If the container is not running then there was a fatal error.

**Comment by Ornias1993** [comment]
> Why would this be useful

To detect any stalls besides exit 1

> How would we implement this

If I would've had a ready to rock solution it would've been a PR, not a feature request.

> There is no web interface

Healthchecks don't require one either

> It’s either running or not

Because program freezes/stalls don't ever happen or something?

> If the container is not running then there was a fatal error

A healthcheck is not for detecting container failure, thats what "restart: on-failure" is for.

**Comment by samwiseg0** [comment]
> To detect any stalls besides exit 1

How would we detect them? 

> If I would've had a ready to rock solution it would've been a PR, not a feature request.

I am not asking for one. You asked for the feature so some idea on what and how to implement would be beneficial in getting the feature request approved. 

> Because program freezes/stalls don't ever happen or something?

To our knowledge this has never happened. Not saying it is not possible but we have not seen this issue in the past. It is hard to code for something generic/nonspecific. If we are not trying to solve a specific problem then it is hard to implement. 

>A healthcheck is not for detecting container failure, thats what "restart: on-failure" is for.

I understand this. This is why I am asking these questions. I am not seeing the benefit of a health check for this very reason. The software is coded to exit if there is a fatal error. Beyond that it will continue to run. If there is an error with a certain module it would be represented in the logs and the data would be missing in the dashboard. I believe this is sufficient in providing user feedback of any issues that may arise. 

I have thought about this in the past but I have not seen the benefits of adding it since typically there is no other states than running, stopped, or failed to start. The only marginal benefit I see is doing a health check for every module individually to see if there are any errors. This seems to be overkill for a simple health check in my opinion. This would also require some large changes in the code just for a simple health check which again I don't see a sufficient benefit.

@DirtyCajunRice Do you have any thoughts on this?

**Comment by Ornias1993** [comment]
Okey, to give some more imput:

You could have the script output the last run time into a file and have a -healthcheck handle to compare that to current time.
If there was too much time between the last run and the current time running -healthcheck you can assume it isn't running properly.

Said idea could be expanded to even include dependencies successes and base the health on that too, but I think just knowing if it ran should be enough (if it ran and a single dependency didn't. that isn't really related to the health of the varken script itself IMHO)
