### ISSUE TITLE
[BUG] Influx server config not accepting DNS hostnames

### ISSUE THREAD

**Issue by MaartenMol** [Boerderij/Varken#66]
When using a dns or container name for the influx url like: unfluxdb, I get the error that it's not correct and needs to be a hostname or ip. When reverting to docker image with tag v1.1 it works like normal.

**Comment by DirtyCajunRice** [comment]
We applied regex style parameters to urls to ensure integrity before creating a session with the host. Hostnames alone will not match this regex as its not an fqdn or IP. If you define an IP you must define a port, if you define a url you MAY define a port. These were both intentional and allow for sane logic in debugging. 

As a side note, i worked in networking support for a long time. When you query within the same layer2 domain, you should always use an IP:PORT over dns whether hostname or fqdn. This removes any issues with dns that cause cascading application failures unnecessarily. when crossing layer3 you should use either an IP:PORT or FQDN. There is never a circumstance where you should rely on hostnames alone. even with dns-search/append applied to your nic

**Comment by MaartenMol** [comment]
So when using Docker I should config the url as: influxdb:8023 for example. And should I ignore the port setting or fill that with the same port?

**Comment by DirtyCajunRice** [comment]
No, IP address or domain name. That is a hostname. And influxdb port is an argument not a url so it is defined as it’s own var

**Comment by MaartenMol** [comment]
You really should reconsider this then. Things like Docker are build to be dynamic. Using container names (hostnames) in configuration is one of the things that makes Docker dynamic. So you are not stuck to static config. With this requirement (IP or domain name) you need to forward ports of the container to your host (to use a domain name) or set a static IP in your Docker environment for that container (to use an IP).

A container does not have a domain name. Using the name of the container in configuration makes your environment dynamic and easy to manage and troubleshoot.

Don't get me wrong, I like Varken. But I just don't get this IP/domain name requirement.

**Comment by samwiseg0** [comment]
Made the change to be able to specify just a hostname.
